---
development:
  cloud_name: 'dhwd6ifyq'
  api_key: '668832472927856'
  api_secret: 'xN4ffAm0lgm8Ew0b68NM4gFTNOs'
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: 'dhwd6ifyq'
  api_key: '668832472927856'
  api_secret: 'xN4ffAm0lgm8Ew0b68NM4gFTNOs'
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: 'dhwd6ifyq'
  api_key: '668832472927856'
  api_secret: 'xN4ffAm0lgm8Ew0b68NM4gFTNOs'
  enhance_image_tag: true
  static_file_support: false